require('dotenv').config();
const fs = require('fs');
const fetch = require('node-fetch');

const today = new Date().toISOString().split('T')[0];
const reportsDir = './reports';
if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir);

async function generateReport() {
  console.log('Generating report for', today);

  const prompt = `You are a Web3 & AI analyst. Write a daily insight report for ${today}.
Include:
1. 🌐 Top AI + Web3 trend today
2. 🔗 One interesting on-chain or protocol development
3. 🤖 How AI is being used in blockchain right now
4. 🚀 One alpha or opportunity worth watching
5. 💡 A thought-provoking question for builders

Format: clean markdown, use emojis, max 400 words. Make it insightful and unique.`;

  const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': 'https://github.com/kimberly-WY/ai-web3-daily-pulse',
      'X-Title': 'AI Web3 Daily Pulse'
    },
    body: JSON.stringify({
      model: 'openrouter/auto',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 600
    })
  });

  const data = await response.json();
  if (!data.choices || !data.choices[0]) {
    console.error('API error:', JSON.stringify(data));
    process.exit(1);
  }

  const content = data.choices[0].message.content;
  const report = `# 🌌 AI + Web3 Daily Pulse — ${today}\n\n${content}\n\n---\n*Generated by AI • Committed by GitHub Actions • [ai-web3-daily-pulse](https://github.com/kimberly-WY/ai-web3-daily-pulse)*\n`;

  fs.writeFileSync(`${reportsDir}/${today}.md`, report);
  console.log('Report saved:', `${reportsDir}/${today}.md`);
}

generateReport().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
